version: '3.8'
services:
  web:
    build: ./FE
    ports:
      - 3000:3000
    image: tele2_web:1
    volumes:
      - ./FE:/app
      - /app/node_modules
  api:
    build: ./BE
    ports:
      - 3001:3001
    image: tele2_api:1
    volumes:
      - ./BE:/app
      - /app/node_modules